version: "0.5.5+1.19.4"
relayBurnNoneFuelItems: true
showItemEmcOrigin: false
showEnchantedBookRepairCost: true
enchantmentEmcConstant: "3260"
emcInMultiplier: "1"
emcOutMultiplier: "1"
mapper.enabled: true
transmutationTable.animated: true
transmutationTable.floorButton: false